apiVersion: apps/v1
kind: Deployment
metadata: 
  name: convert-temperature
spec:
  replicas: 4
  selector:
    matchLabels:
      app: convert-temperature
  template:
    metadata:
      labels:
        app: convert-temperature
    spec:
      containers:
        - name: convert-temperature
          image: jehmes/conversao-temperatura:v1
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: convert-temperature
spec:
  selector:
    app: convert-temperature
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort